import mongoose, { Schema } from "mongoose"

import { GST_SPLIT_MODES, INVOICE_STATUSES } from "../constants/invoices.js"

const invoiceSchema = new Schema(
  {
    organizationId: {
      type: Schema.Types.ObjectId,
      ref: "Organization",
      required: true,
      index: true,
    },
    clientId: {
      type: Schema.Types.ObjectId,
      ref: "Client",
      required: true,
      index: true,
    },
    joiningId: {
      type: Schema.Types.ObjectId,
      ref: "Joining",
      default: null,
      index: true,
    },
    candidateId: {
      type: Schema.Types.ObjectId,
      ref: "Candidate",
      default: null,
      index: true,
    },
    mandateId: {
      type: Schema.Types.ObjectId,
      ref: "RecruitmentMandate",
      default: null,
      index: true,
    },
    invoiceNumber: {
      type: String,
      required: true,
      trim: true,
      uppercase: true,
      maxlength: 24,
    },
    invoiceDate: {
      type: Date,
      required: true,
      index: true,
    },
    dueDate: {
      type: Date,
      default: null,
      index: true,
    },
    joiningDate: {
      type: Date,
      default: null,
    },
    /** Professional fee before GST. For legacy invoices equals amount when tax fields empty. */
    professionalFee: {
      type: Number,
      min: 0,
      default: null,
    },
    gstRatePercent: {
      type: Number,
      min: 0,
      max: 100,
      default: null,
    },
    gstSplitMode: {
      type: String,
      enum: [...GST_SPLIT_MODES, ""],
      default: "",
    },
    cgst: { type: Number, min: 0, default: 0 },
    sgst: { type: Number, min: 0, default: 0 },
    igst: { type: Number, min: 0, default: 0 },
    gstAmount: { type: Number, min: 0, default: 0 },
    /** Total invoice amount (professional fee + GST). Legacy invoices store total here. */
    amount: {
      type: Number,
      min: 0,
      required: true,
    },
    paidAmount: {
      type: Number,
      min: 0,
      default: 0,
    },
    outstandingAmount: {
      type: Number,
      min: 0,
      default: 0,
    },
    feeType: {
      type: String,
      trim: true,
      maxlength: 20,
      default: "",
    },
    feeBasisCtc: {
      type: Number,
      min: 0,
      default: null,
    },
    autoGenerated: {
      type: Boolean,
      default: false,
      index: true,
    },
    status: {
      type: String,
      enum: INVOICE_STATUSES,
      required: true,
      default: "SENT",
      index: true,
    },
    remarks: {
      type: String,
      trim: true,
      maxlength: 4000,
      default: "",
    },
  },
  { timestamps: true }
)

invoiceSchema.index({ organizationId: 1, invoiceNumber: 1 }, { unique: true })
invoiceSchema.index({ organizationId: 1, clientId: 1, invoiceDate: -1 })
invoiceSchema.index({ organizationId: 1, status: 1, invoiceDate: -1 })
invoiceSchema.index(
  { organizationId: 1, joiningId: 1 },
  {
    unique: true,
    partialFilterExpression: {
      joiningId: { $type: "objectId" },
      autoGenerated: true,
      status: { $ne: "CANCELLED" },
    },
  }
)

export const InvoiceModel = mongoose.model("Invoice", invoiceSchema)
