import mongoose from "mongoose"

import {
  DEFAULT_GST_RATE_PERCENT,
  DEFAULT_PAYMENT_TERMS_DAYS,
  DEFAULT_REPLACEMENT_PERIOD_DAYS,
} from "../constants/agreements.js"
import type { GstSplitMode } from "../constants/invoices.js"
import { ClientAgreementModel } from "../models/client-agreement.model.js"
import { GuaranteeFollowUpModel } from "../models/guarantee-follow-up.model.js"
import { InvoiceModel } from "../models/invoice.model.js"
import { OfferModel } from "../models/offer.model.js"
import { RecruitmentMandateModel } from "../models/recruitment-mandate.model.js"
import type { AuthContext } from "../types/auth.js"
import { recordActivity } from "./activity.js"
import { recordAudit } from "./audit.js"
import { planGuaranteeMilestones } from "./guarantee-period.js"
import { generateInvoiceNumber } from "./invoice-number.js"
import { calculatePlacementFee, roundMoney } from "./placement-fee.js"

type JoiningLike = {
  _id: mongoose.Types.ObjectId | string
  organizationId: mongoose.Types.ObjectId | string
  clientId: mongoose.Types.ObjectId | string
  candidateId: mongoose.Types.ObjectId | string
  mandateId: mongoose.Types.ObjectId | string
  offerId: mongoose.Types.ObjectId | string
  joiningDate: Date
}

function asObjectId(value: mongoose.Types.ObjectId | string) {
  return typeof value === "string" ? new mongoose.Types.ObjectId(value) : value
}

/**
 * Idempotent: create auto invoice + guarantee when joining is CONFIRMED/JOINED.
 * Does not create a second auto-generated invoice for the same joining.
 */
export async function ensureJoiningSideEffects(auth: AuthContext, joining: JoiningLike) {
  const joiningId = String(joining._id)
  const organizationId = String(joining.organizationId)
  const orgOid = asObjectId(joining.organizationId)
  const joiningOid = asObjectId(joining._id)
  const clientOid = asObjectId(joining.clientId)
  const candidateOid = asObjectId(joining.candidateId)
  const mandateOid = asObjectId(joining.mandateId)
  const offerOid = asObjectId(joining.offerId)

  let invoiceId = ""
  let guaranteeId = ""

  const existingInvoice = await InvoiceModel.findOne({
    organizationId: orgOid,
    joiningId: joiningOid,
    autoGenerated: true,
    status: { $ne: "CANCELLED" },
  }).select("_id invoiceNumber")

  const existingGuarantee = await GuaranteeFollowUpModel.findOne({
    organizationId: orgOid,
    joiningId: joiningOid,
  }).select("_id")

  const mandate = await RecruitmentMandateModel.findOne({
    _id: mandateOid,
    organizationId: orgOid,
  }).select(
    "_id agreementId recruitmentFee feeType replacementPeriodDays paymentTermsDays mandateNumber position"
  )

  const agreement = mandate?.agreementId
    ? await ClientAgreementModel.findOne({
        _id: mandate.agreementId,
        organizationId: orgOid,
      }).select("commercialTerms ownershipPeriodMonths replacementPeriodDays")
    : null

  const offer = await OfferModel.findOne({
    _id: offerOid,
    organizationId: orgOid,
  }).select("offeredCTC offeredDesignation")

  const feeType = String(mandate?.feeType ?? agreement?.commercialTerms?.feeType ?? "PERCENTAGE")
  const recruitmentFee = Number(
    mandate?.recruitmentFee ?? agreement?.commercialTerms?.recruitmentFee ?? 0
  )
  const paymentTermsDays = Number(
    mandate?.paymentTermsDays ??
      agreement?.commercialTerms?.paymentTermsDays ??
      DEFAULT_PAYMENT_TERMS_DAYS
  )
  const gstRatePercent = Number(
    agreement?.commercialTerms?.gstRatePercent ?? DEFAULT_GST_RATE_PERCENT
  )
  const gstSplitMode = String(
    agreement?.commercialTerms?.gstSplitMode ?? "CGST_SGST"
  ) as GstSplitMode
  const replacementPeriodDays = Number(
    mandate?.replacementPeriodDays ??
      agreement?.replacementPeriodDays ??
      DEFAULT_REPLACEMENT_PERIOD_DAYS
  )
  const offeredCtc = Number(offer?.offeredCTC ?? 0)
  const invoiceDate = new Date()
  const fee = calculatePlacementFee({
    feeType,
    recruitmentFee,
    offeredAnnualCtc: offeredCtc,
    gstRatePercent,
    gstSplitMode,
    invoiceDate,
    paymentTermsDays,
  })

  if (existingInvoice) {
    invoiceId = String(existingInvoice._id)
  } else {
    try {
      const created = await InvoiceModel.create({
        organizationId: orgOid,
        clientId: clientOid,
        joiningId: joiningOid,
        candidateId: candidateOid,
        mandateId: mandateOid,
        invoiceNumber: await generateInvoiceNumber(organizationId),
        invoiceDate,
        dueDate: fee.dueDate,
        joiningDate: joining.joiningDate,
        professionalFee: fee.professionalFee,
        gstRatePercent: fee.gstRatePercent,
        gstSplitMode,
        cgst: fee.cgst,
        sgst: fee.sgst,
        igst: fee.igst,
        gstAmount: fee.gstAmount,
        amount: fee.totalAmount,
        paidAmount: 0,
        outstandingAmount: fee.totalAmount,
        feeType,
        feeBasisCtc: offeredCtc || null,
        autoGenerated: true,
        status: "ISSUED",
        remarks: "Auto-generated on joining confirmation",
      })
      invoiceId = String(created._id)
      await recordActivity(organizationId, {
        title: `Invoice ${created.invoiceNumber} generated`,
        detail: `Professional fee ${fee.professionalFee} + GST ${fee.gstAmount}`,
        tone: "success",
      })
      await recordAudit(auth, {
        module: "INVOICES",
        action: "GENERATED",
        recordId: invoiceId,
        newData: {
          invoiceNumber: created.invoiceNumber,
          amount: fee.totalAmount,
          joiningId,
          autoGenerated: true,
        },
      })
    } catch (error) {
      const raced = await InvoiceModel.findOne({
        organizationId: orgOid,
        joiningId: joiningOid,
        autoGenerated: true,
        status: { $ne: "CANCELLED" },
      }).select("_id")
      if (!raced) throw error
      invoiceId = String(raced._id)
    }
  }

  if (existingGuarantee) {
    guaranteeId = String(existingGuarantee._id)
  } else {
    const plan = planGuaranteeMilestones(joining.joiningDate, replacementPeriodDays)
    try {
      const created = await GuaranteeFollowUpModel.create({
        organizationId: orgOid,
        candidateId: candidateOid,
        joiningId: joiningOid,
        mandateId: mandateOid,
        clientId: clientOid,
        joiningDate: joining.joiningDate,
        guaranteeStartDate: plan.guaranteeStartDate,
        guaranteeEndDate: plan.guaranteeEndDate,
        milestone30Enabled: plan.milestone30Enabled,
        milestone60Enabled: plan.milestone60Enabled,
        milestone90Enabled: plan.milestone90Enabled,
        replacementPeriodDays: plan.replacementPeriodDays,
        retentionStatus: "IN_PROGRESS",
      })
      guaranteeId = String(created._id)
      await recordActivity(organizationId, {
        title: "Guarantee tracking started",
        detail: `${plan.replacementPeriodDays} days from joining`,
        tone: "success",
      })
      await recordAudit(auth, {
        module: "GUARANTEES",
        action: "CREATED",
        recordId: guaranteeId,
        newData: {
          joiningId,
          guaranteeEndDate: plan.guaranteeEndDate,
          replacementPeriodDays: plan.replacementPeriodDays,
        },
      })
    } catch (error) {
      const raced = await GuaranteeFollowUpModel.findOne({
        organizationId: orgOid,
        joiningId: joiningOid,
      }).select("_id")
      if (!raced) throw error
      guaranteeId = String(raced._id)
    }
  }

  await OfferModel.updateOne(
    { _id: offerOid, organizationId: orgOid },
    {
      $set: {
        joiningStatus: "JOINED",
        actualJoiningDate: joining.joiningDate,
      },
    }
  ).catch(() => undefined)

  return {
    invoiceId,
    guaranteeId,
    professionalFee: roundMoney(fee.professionalFee),
    totalAmount: roundMoney(fee.totalAmount),
  }
}
