import { USER_ROLES, type UserRole } from "./roles.js"

export const PERMISSIONS = {
  DASHBOARD_READ: "dashboard:read",

  EMPLOYEES_READ: "employees:read",
  EMPLOYEES_READ_TEAM: "employees:read_team",
  EMPLOYEES_READ_SELF: "employees:read_self",
  EMPLOYEES_MANAGE: "employees:manage",

  DEPARTMENTS_READ: "departments:read",
  DEPARTMENTS_MANAGE: "departments:manage",

  DESIGNATIONS_READ: "designations:read",
  DESIGNATIONS_MANAGE: "designations:manage",

  ATTENDANCE_READ: "attendance:read",
  ATTENDANCE_READ_TEAM: "attendance:read_team",
  ATTENDANCE_READ_SELF: "attendance:read_self",
  ATTENDANCE_MANAGE: "attendance:manage",
  ATTENDANCE_CHECK_IN: "attendance:check_in",

  LEAVE_READ: "leave:read",
  LEAVE_READ_TEAM: "leave:read_team",
  LEAVE_READ_SELF: "leave:read_self",
  LEAVE_CREATE_SELF: "leave:create_self",
  LEAVE_MANAGE: "leave:manage",
  LEAVE_APPROVE_TEAM: "leave:approve_team",

  DOCUMENTS_READ: "documents:read",
  DOCUMENTS_READ_SELF: "documents:read_self",
  DOCUMENTS_MANAGE: "documents:manage",

  ASSETS_READ: "assets:read",
  ASSETS_READ_SELF: "assets:read_self",
  ASSETS_MANAGE: "assets:manage",

  ANNOUNCEMENTS_READ: "announcements:read",
  ANNOUNCEMENTS_MANAGE: "announcements:manage",

  PAYROLL_READ: "payroll:read",
  PAYROLL_MANAGE: "payroll:manage",

  RECRUITMENT_READ: "recruitment:read",
  RECRUITMENT_MANAGE: "recruitment:manage",

  PERFORMANCE_READ: "performance:read",
  PERFORMANCE_READ_TEAM: "performance:read_team",
  PERFORMANCE_READ_SELF: "performance:read_self",
  PERFORMANCE_MANAGE: "performance:manage",

  REPORTS_READ: "reports:read",

  SETTINGS_READ: "settings:read",
  SETTINGS_MANAGE: "settings:manage",

  DESIGN_SYSTEM_READ: "design_system:read",
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

export const ALL_PERMISSIONS = Object.values(PERMISSIONS)

const HR_ADMIN_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_READ,
  PERMISSIONS.EMPLOYEES_READ,
  PERMISSIONS.EMPLOYEES_READ_SELF,
  PERMISSIONS.EMPLOYEES_MANAGE,
  PERMISSIONS.DEPARTMENTS_READ,
  PERMISSIONS.DEPARTMENTS_MANAGE,
  PERMISSIONS.DESIGNATIONS_READ,
  PERMISSIONS.DESIGNATIONS_MANAGE,
  PERMISSIONS.ATTENDANCE_READ,
  PERMISSIONS.ATTENDANCE_READ_SELF,
  PERMISSIONS.ATTENDANCE_MANAGE,
  PERMISSIONS.ATTENDANCE_CHECK_IN,
  PERMISSIONS.LEAVE_READ,
  PERMISSIONS.LEAVE_READ_SELF,
  PERMISSIONS.LEAVE_CREATE_SELF,
  PERMISSIONS.LEAVE_MANAGE,
  PERMISSIONS.DOCUMENTS_READ,
  PERMISSIONS.DOCUMENTS_READ_SELF,
  PERMISSIONS.DOCUMENTS_MANAGE,
  PERMISSIONS.ASSETS_READ,
  PERMISSIONS.ASSETS_READ_SELF,
  PERMISSIONS.ASSETS_MANAGE,
  PERMISSIONS.ANNOUNCEMENTS_READ,
  PERMISSIONS.ANNOUNCEMENTS_MANAGE,
  PERMISSIONS.PAYROLL_READ,
  PERMISSIONS.PAYROLL_MANAGE,
  PERMISSIONS.RECRUITMENT_READ,
  PERMISSIONS.RECRUITMENT_MANAGE,
  PERMISSIONS.PERFORMANCE_READ,
  PERMISSIONS.PERFORMANCE_READ_SELF,
  PERMISSIONS.PERFORMANCE_MANAGE,
  PERMISSIONS.REPORTS_READ,
  PERMISSIONS.SETTINGS_READ,
  PERMISSIONS.SETTINGS_MANAGE,
] as const satisfies readonly Permission[]

const MANAGER_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_READ,
  PERMISSIONS.EMPLOYEES_READ_TEAM,
  PERMISSIONS.EMPLOYEES_READ_SELF,
  PERMISSIONS.ATTENDANCE_READ_TEAM,
  PERMISSIONS.ATTENDANCE_READ_SELF,
  PERMISSIONS.ATTENDANCE_CHECK_IN,
  PERMISSIONS.LEAVE_READ_TEAM,
  PERMISSIONS.LEAVE_READ_SELF,
  PERMISSIONS.LEAVE_CREATE_SELF,
  PERMISSIONS.LEAVE_APPROVE_TEAM,
  PERMISSIONS.DOCUMENTS_READ_SELF,
  PERMISSIONS.ASSETS_READ_SELF,
  PERMISSIONS.ANNOUNCEMENTS_READ,
  PERMISSIONS.PERFORMANCE_READ_TEAM,
  PERMISSIONS.PERFORMANCE_READ_SELF,
  PERMISSIONS.SETTINGS_READ,
] as const satisfies readonly Permission[]

const EMPLOYEE_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_READ,
  PERMISSIONS.EMPLOYEES_READ_SELF,
  PERMISSIONS.ATTENDANCE_READ_SELF,
  PERMISSIONS.ATTENDANCE_CHECK_IN,
  PERMISSIONS.LEAVE_READ_SELF,
  PERMISSIONS.LEAVE_CREATE_SELF,
  PERMISSIONS.DOCUMENTS_READ_SELF,
  PERMISSIONS.ASSETS_READ_SELF,
  PERMISSIONS.ANNOUNCEMENTS_READ,
  PERMISSIONS.PERFORMANCE_READ_SELF,
  PERMISSIONS.SETTINGS_READ,
] as const satisfies readonly Permission[]

export const ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {
  [USER_ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
  [USER_ROLES.HR_ADMIN]: HR_ADMIN_PERMISSIONS,
  [USER_ROLES.MANAGER]: MANAGER_PERMISSIONS,
  [USER_ROLES.EMPLOYEE]: EMPLOYEE_PERMISSIONS,
}
